function branches = buildJA_minorLoopBranchConditions(Htips, repetitions)
%BUILDJA_MINORLOOPBRANCHCONDITIONS Describe the monotonic legs of minor loops.
%
%   branches = buildJA_minorLoopBranchConditions(Htips, repetitions)
%
%   The function prepares the sequence of branches for the Playground
%   minor-loop workflow. Htips is sorted in ascending order before the
%   branch list is generated.

    if nargin < 2 || isempty(repetitions)
        repetitions = 1;
    end

    Htips = sort(double(Htips(:)), 'ascend');
    repetitions = max(0, round(repetitions));

    if isempty(Htips) || any(~isfinite(Htips)) || any(Htips <= 0)
        error('buildJA_minorLoopBranchConditions:InvalidTipFields', ...
            'Htips must be a non-empty vector of finite positive values.');
    end

    branches = struct( ...
        'i', {}, ...
        'loopIndex', {}, ...
        'branchType', {}, ...
        'Hstart', {}, ...
        'Hend', {}, ...
        'Mstart', {}, ...
        'delta', {}, ...
        'MstartSource', {}, ...
        'usesPreviousBranchEnd', {});

    nextIndex = 1;
    previousPositiveTip = 0;
    for loopIndex = 1:numel(Htips)
        Htip = Htips(loopIndex);

        if loopIndex == 1
            branches(nextIndex) = localMakeBranch( ...
                nextIndex, loopIndex, "initial", 0, Htip, NaN, "initial magnetization", false); %#ok<AGROW>
            nextIndex = nextIndex + 1;
        else
            branches(nextIndex) = localMakeBranch( ...
                nextIndex, loopIndex, "bridge", previousPositiveTip, Htip, NaN, "bridge to next amplitude", true); %#ok<AGROW>
            nextIndex = nextIndex + 1;
        end

        for rep = 1:repetitions
            branches(nextIndex) = localMakeBranch( ...
                nextIndex, loopIndex, "left", Htip, -Htip, NaN, "minor loop left branch", true); %#ok<AGROW>
            nextIndex = nextIndex + 1;

            branches(nextIndex) = localMakeBranch( ...
                nextIndex, loopIndex, "right", -Htip, Htip, NaN, "minor loop right branch", true); %#ok<AGROW>
            nextIndex = nextIndex + 1;
        end

        previousPositiveTip = Htip;
    end
end

function branch = localMakeBranch(i, loopIndex, branchType, Hstart, Hend, Mstart, MstartSource, usesPreviousBranchEnd)
    branch = struct( ...
        'i', i, ...
        'loopIndex', loopIndex, ...
        'branchType', branchType, ...
        'Hstart', Hstart, ...
        'Hend', Hend, ...
        'Mstart', Mstart, ...
        'delta', sign(Hend - Hstart), ...
        'MstartSource', MstartSource, ...
        'usesPreviousBranchEnd', usesPreviousBranchEnd);
end
