function branches = buildJA_majorLoopBranchConditions(startMode, Hstart, Mstart, HtipMajor, repetitions)
%BUILDJA_MAJORLOOPBRANCHCONDITIONS Describe the monotonic legs of a major loop.
%
%   branches = buildJA_majorLoopBranchConditions(startMode, Hstart, Mstart, HtipMajor, repetitions)
%
%   The function does not solve the ODE. It only prepares the branch
%   parameters needed by solveJA_monotonic:
%     [Hsol, Msol] = solveJA_monotonic(Hstart, Hend, Mstart, params, delta, opts)
%
%   Inputs:
%     startMode    : "Demagnetized", "Tip point", or "User-defined"
%     Hstart       : starting applied field for the first leg [A/m]
%     Mstart       : starting magnetization for the first leg [A/m]
%     HtipMajor    : positive tip field of the major loop [A/m]
%     repetitions  : number of full cycles after the first leg
%
%   Output:
%     branches     : struct array with the fields
%                    - i
%                    - branchType
%                    - Hstart
%                    - Hend
%                    - Mstart
%                    - delta
%                    - MstartSource
%                    - usesPreviousBranchEnd

    if nargin < 5 || isempty(repetitions)
        repetitions = 1;
    end

    startMode = string(startMode);
    if ~isscalar(startMode)
        error('buildJA_majorLoopBranchConditions:InvalidStartMode', ...
            'startMode must be a scalar string or character vector.');
    end

    isTipPointStart = contains(lower(startMode), "tip point");
    if isTipPointStart
        if ~(isscalar(HtipMajor) && isfinite(HtipMajor) && HtipMajor > 0)
            error('buildJA_majorLoopBranchConditions:InvalidInputs', ...
                'HtipMajor must be a finite positive scalar.');
        end
    else
        if ~(isscalar(Hstart) && isfinite(Hstart) && isscalar(Mstart) && isfinite(Mstart) ...
                && isscalar(HtipMajor) && isfinite(HtipMajor) && HtipMajor > 0)
            error('buildJA_majorLoopBranchConditions:InvalidInputs', ...
                'Hstart, Mstart and HtipMajor must be finite scalars and HtipMajor must be positive.');
        end
    end

    if ~(isscalar(repetitions) && isfinite(repetitions) && repetitions >= 0)
        error('buildJA_majorLoopBranchConditions:InvalidRepetitions', ...
            'repetitions must be a non-negative scalar.');
    end

    repetitions = round(repetitions);

    branches = struct( ...
        'i', {}, ...
        'branchType', {}, ...
        'Hstart', {}, ...
        'Hend', {}, ...
        'Mstart', {}, ...
        'delta', {}, ...
        'MstartSource', {}, ...
        'usesPreviousBranchEnd', {});

    nextIndex = 1;
    if ~isTipPointStart
        branches(nextIndex) = localMakeBranch( ...
            0, ...
            "initial", ...
            Hstart, ...
            HtipMajor, ...
            Mstart, ...
            "starting point", ...
            false);
        nextIndex = nextIndex + 1;
    end

    for i = 1:(2 * repetitions)
        Hstart_i = (-1)^(i + 1) * HtipMajor;
        Hend_i = (-1)^i * HtipMajor;
        branchType = "left";
        if mod(i, 2) == 0
            branchType = "right";
        end

        branches(nextIndex) = localMakeBranch( ...
            i, ...
            branchType, ...
            Hstart_i, ...
            Hend_i, ...
            NaN, ...
            "previous branch end", ...
            true);
        nextIndex = nextIndex + 1;
    end
end

function branch = localMakeBranch(i, branchType, Hstart, Hend, Mstart, MstartSource, usesPreviousBranchEnd)
    branch = struct( ...
        'i', i, ...
        'branchType', branchType, ...
        'Hstart', Hstart, ...
        'Hend', Hend, ...
        'Mstart', Mstart, ...
        'delta', sign(Hend - Hstart), ...
        'MstartSource', MstartSource, ...
        'usesPreviousBranchEnd', usesPreviousBranchEnd);
end
