function branches = build_ja_major_loop_branch_conditions(start_mode, Hstart, Mstart, HtipMajor, repetitions)
%BUILD_JA_MAJOR_LOOP_BRANCH_CONDITIONS Describe the monotonic legs of a major loop.
%
%   branches = build_ja_major_loop_branch_conditions(start_mode, Hstart, Mstart, HtipMajor, repetitions)
%
%   The function does not solve the ODE. It only prepares the branch
%   parameters needed by solve_ja_monotonic:
%     [Hsol, Msol] = solve_ja_monotonic(Hstart, Hend, Mstart, params, delta, opts)
%
%   Inputs:
%     start_mode    : "Demagnetized", "Tip point", or "User-defined"
%     Hstart       : starting applied field for the first leg [A/m]
%     Mstart       : starting magnetization for the first leg [A/m]
%     HtipMajor    : positive tip field of the major loop [A/m]
%     repetitions  : number of full cycles after the first leg
%
%   Output:
%     branches     : struct array with the fields
%                    - i
%                    - branch_type
%                    - Hstart
%                    - Hend
%                    - Mstart
%                    - delta
%                    - Mstart_source
%                    - uses_previous_branch_end

    if nargin < 5 || isempty(repetitions)
        repetitions = 1;
    end

    start_mode = string(start_mode);
    if ~isscalar(start_mode)
        error('build_ja_major_loop_branch_conditions:InvalidStartMode', ...
            'start_mode must be a scalar string or character vector.');
    end

    is_tip_point_start = contains(lower(start_mode), "tip point");
    if is_tip_point_start
        if ~(isscalar(HtipMajor) && isfinite(HtipMajor) && HtipMajor > 0)
            error('build_ja_major_loop_branch_conditions:InvalidInputs', ...
                'HtipMajor must be a finite positive scalar.');
        end
    else
        if ~(isscalar(Hstart) && isfinite(Hstart) && isscalar(Mstart) && isfinite(Mstart) ...
                && isscalar(HtipMajor) && isfinite(HtipMajor) && HtipMajor > 0)
            error('build_ja_major_loop_branch_conditions:InvalidInputs', ...
                'Hstart, Mstart and HtipMajor must be finite scalars and HtipMajor must be positive.');
        end
    end

    if ~(isscalar(repetitions) && isfinite(repetitions) && repetitions >= 0)
        error('build_ja_major_loop_branch_conditions:InvalidRepetitions', ...
            'repetitions must be a non-negative scalar.');
    end

    repetitions = round(repetitions);

    branches = struct( ...
        'i', {}, ...
        'branch_type', {}, ...
        'Hstart', {}, ...
        'Hend', {}, ...
        'Mstart', {}, ...
        'delta', {}, ...
        'Mstart_source', {}, ...
        'uses_previous_branch_end', {});

    next_index = 1;
    if ~is_tip_point_start
        branches(next_index) = local_make_branch( ...
            0, ...
            "initial", ...
            Hstart, ...
            HtipMajor, ...
            Mstart, ...
            "starting point", ...
            false);
        next_index = next_index + 1;
    end

    for i = 1:(2 * repetitions)
        Hstart_i = (-1)^(i + 1) * HtipMajor;
        Hend_i = (-1)^i * HtipMajor;
        branch_type = "left";
        if mod(i, 2) == 0
            branch_type = "right";
        end

        branches(next_index) = local_make_branch( ...
            i, ...
            branch_type, ...
            Hstart_i, ...
            Hend_i, ...
            NaN, ...
            "previous branch end", ...
            true);
        next_index = next_index + 1;
    end
end

function branch = local_make_branch(i, branch_type, Hstart, Hend, Mstart, Mstart_source, uses_previous_branch_end)
    branch = struct( ...
        'i', i, ...
        'branch_type', branch_type, ...
        'Hstart', Hstart, ...
        'Hend', Hend, ...
        'Mstart', Mstart, ...
        'delta', sign(Hend - Hstart), ...
        'Mstart_source', Mstart_source, ...
        'uses_previous_branch_end', uses_previous_branch_end);
end
