function branches = build_ja_minor_loop_branch_conditions(Htips, repetitions)
%BUILD_JA_MINOR_LOOP_BRANCH_CONDITIONS Describe the monotonic legs of minor loops.
%
%   branches = build_ja_minor_loop_branch_conditions(Htips, repetitions)
%
%   The function prepares the sequence of branches for the Playground
%   minor-loop workflow. Htips is sorted in ascending order before the
%   branch list is generated.

    if nargin < 2 || isempty(repetitions)
        repetitions = 1;
    end

    Htips = sort(double(Htips(:)), 'ascend');
    repetitions = max(0, round(repetitions));

    if isempty(Htips) || any(~isfinite(Htips)) || any(Htips <= 0)
        error('build_ja_minor_loop_branch_conditions:InvalidTipFields', ...
            'Htips must be a non-empty vector of finite positive values.');
    end

    branches = struct( ...
        'i', {}, ...
        'loop_index', {}, ...
        'branch_type', {}, ...
        'Hstart', {}, ...
        'Hend', {}, ...
        'Mstart', {}, ...
        'delta', {}, ...
        'Mstart_source', {}, ...
        'uses_previous_branch_end', {});

    next_index = 1;
    previous_positive_tip = 0;
    for loop_index = 1:numel(Htips)
        Htip = Htips(loop_index);

        if loop_index == 1
            branches(next_index) = local_make_branch( ...
                next_index, loop_index, "initial", 0, Htip, NaN, "initial magnetization", false); %#ok<AGROW>
            next_index = next_index + 1;
        else
            branches(next_index) = local_make_branch( ...
                next_index, loop_index, "bridge", previous_positive_tip, Htip, NaN, "bridge to next amplitude", true); %#ok<AGROW>
            next_index = next_index + 1;
        end

        for rep = 1:repetitions
            branches(next_index) = local_make_branch( ...
                next_index, loop_index, "left", Htip, -Htip, NaN, "minor loop left branch", true); %#ok<AGROW>
            next_index = next_index + 1;

            branches(next_index) = local_make_branch( ...
                next_index, loop_index, "right", -Htip, Htip, NaN, "minor loop right branch", true); %#ok<AGROW>
            next_index = next_index + 1;
        end

        previous_positive_tip = Htip;
    end
end

function branch = local_make_branch(i, loop_index, branch_type, Hstart, Hend, Mstart, Mstart_source, uses_previous_branch_end)
    branch = struct( ...
        'i', i, ...
        'loop_index', loop_index, ...
        'branch_type', branch_type, ...
        'Hstart', Hstart, ...
        'Hend', Hend, ...
        'Mstart', Mstart, ...
        'delta', sign(Hend - Hstart), ...
        'Mstart_source', Mstart_source, ...
        'uses_previous_branch_end', uses_previous_branch_end);
end
